WIP: improve modify method
* Update to latest dcmjs to handle error listed below
* add `--logLevel` option to suppress warnings
* update walk.py testscript to use --logLevel option


```
C:\TelixTools\dcmjs-commands\node_modules\dcmjs\build\dcmjs.js:8419
                  if (isString) log.log(errmsg);else throw new Error(errmsg);
                                                           ^

Error: Value exceeds max length, vr: CS, value: [object ArrayBuffer], length: undefined
    at CodeString.writeBytes (C:\TelixTools\dcmjs-commands\node_modules\dcmjs\build\dcmjs.js:8419:53)
    at CodeString.writeBytes (C:\TelixTools\dcmjs-commands\node_modules\dcmjs\build\dcmjs.js:8496:94)
    at Tag.write (C:\TelixTools\dcmjs-commands\node_modules\dcmjs\build\dcmjs.js:8083:27)
    at C:\TelixTools\dcmjs-commands\node_modules\dcmjs\build\dcmjs.js:10170:25
    at Array.forEach (<anonymous>)
    at Function.write (C:\TelixTools\dcmjs-commands\node_modules\dcmjs\build\dcmjs.js:10165:19)
    at DicomDict.write (C:\TelixTools\dcmjs-commands\node_modules\dcmjs\build\dcmjs.js:10310:21)
    at writeDicom (file:///C:/TelixTools/dcmjs-commands/src/index.js:15:33)
    at Command.<anonymous> (file:///C:/TelixTools/dcmjs-commands/bin/dcmjs.js:43:5)
    at Command.listener [as _actionHandler] (C:\TelixTools\dcmjs-commands\node_modules\commander\lib\command.js:542:17)

Node.js v18.19.0
```